[package]
name = "rustysdf"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
path = "src/lib.rs"

[dependencies]
gm_ext_wire = { path = "crates/gm_ext_wire" }
rustybuzz = "0.20"
unicode-bidi = "0.3"
unicode-linebreak = "0.1"
fdsm = { path = "crates/fdsm" }
fdsm-ttf-parser = { path = "crates/fdsm-ttf-parser" }
image = { version = "0.25", default-features = false }
nalgebra = { version = "0.34", default-features = false, features = ["std"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
log = "0.4"

[profile.release]
lto = "thin"
strip = true
panic = "unwind"
